export type McmProduct = {
  id: string;
  kind: "EXHIBITION EDITION" | "MCM ICON" | "CRAFT COLLABORATION" | "MCM COLLECTION";
  name: string;
  description: string;
  officialUrl: string;
  image: string;
  tags: string[];
};

export const mcmProductCatalog: McmProduct[] = [
  { id: "indenya-bearbrick", kind: "EXHIBITION EDITION", name: "MCM X BE@RBRICK 인덴-야 400%", description: "사슴가죽과 옻칠 공예로 비세토스 모티프를 표현한 컬렉터 피스", officialUrl: "https://kr.mcmworldwide.com/ko_KR/%EC%8B%A0%EC%83%81%ED%92%88/bearbrick-in-mcm-wonderland", image: "/products/mcm-bearbrick-indenya.jpg", tags: ["BE@RBRICK", "인덴-야", "옻칠", "가죽", "공예", "컬렉터", "브라운"] },
  { id: "bearbrick-aren", kind: "EXHIBITION EDITION", name: "MCM X BE@RBRICK 참이 있는 Aren 숄더백", description: "BE@RBRICK 참과 MCM의 실용적인 미니 실루엣을 결합한 전시 연계 아이템", officialUrl: "https://jp.mcmworldwide.com/en_JP/men/bags/messengers-crossbody-bags/mcm-x-be%40rbrick-aren-shoulder-bag-with-charm/MMSFATA01EG001.html", image: "/products/mcm-bearbrick-aren.jpg", tags: ["BE@RBRICK", "Aren", "숄더백", "나일론", "오리가미", "그레이", "미니멀"] },
  { id: "stark-visetos", kind: "MCM ICON", name: "스타크 사이드 스터드 비세토스 백팩", description: "시그니처 비세토스 캔버스와 피라미드 스터드가 만난 MCM 아이콘", officialUrl: "https://kr.mcmworldwide.com/ko_KR/mcm-icons/stark-backpacks", image: "/products/mcm-stark-visetos.jpg", tags: ["Stark", "비세토스", "백팩", "여행", "모노그램", "스터드", "꼬냑"] },
  { id: "indenya-airpods", kind: "CRAFT COLLABORATION", name: "MCM x INDEN-YA AirPods Pro Case", description: "일본 고슈 인덴의 가죽·옻칠 기법을 담은 MCM 테크 액세서리", officialUrl: "https://jp.mcmworldwide.com/en_JP/lifestyle/tech-accessories/mcm-x-inden-ya-airpods-pro-case/MXZGSTA30NR001.html", image: "/products/mcm-indenya-airpods.jpg", tags: ["인덴-야", "옻칠", "가죽", "테크", "소품", "공예", "브라운"] },
  { id: "bearbrick-black-set", kind: "EXHIBITION EDITION", name: "MCM X BE@RBRICK 100% & 400% Set", description: "블랙 컬러와 MCM 모노그램을 결합한 두 가지 크기의 컬렉터 세트", officialUrl: "https://us.mcmworldwide.com/en_US/mcm-x-be%40rbrick-100%25-400%25-set/MEZESJA02BK001.html", image: "/products/mcm-bearbrick-black-set.jpg", tags: ["BE@RBRICK", "블랙", "모노그램", "피규어", "컬렉터", "팝아트"] },
  { id: "bearbrick-ken-yashiki", kind: "EXHIBITION EDITION", name: "MCM X BE@RBRICK Ken Yashiki 100% & 400% Set", description: "켄 야시키의 기억과 패턴을 MCM 컬렉터 피규어로 옮긴 협업 세트", officialUrl: "https://jp.mcmworldwide.com/ja_JP/%E3%82%AE%E3%83%95%E3%83%88/%E3%82%B9%E3%83%A2%E3%83%BC%E3%83%AB%E3%82%AE%E3%83%95%E3%83%88/mcm-x-be%40rbrick-%E8%B0%B7%E6%95%B7%E8%AC%99-100%EF%BC%85400%EF%BC%85-%E3%82%BB%E3%83%83%E3%83%88/MEZFAMM11MT001.html", image: "/products/mcm-bearbrick-ken-yashiki.jpg", tags: ["BE@RBRICK", "켄 야시키", "기억", "패턴", "멀티컬러", "토끼", "컬렉터"] },
  { id: "bearbrick-tshirt", kind: "MCM COLLECTION", name: "MCM X BE@RBRICK 400% Print T-Shirt", description: "실제 400% 피규어 크기의 그래픽과 비세토스 모노그램을 담은 코튼 티셔츠", officialUrl: "https://jp.mcmworldwide.com/en_JP/men/ready-to-wear/tops-t-shirts/mcm-x-be%40rbrick-400%25-print-t-shirt/MHTFAMM08WT00L.html", image: "/products/mcm-bearbrick-tshirt.jpg", tags: ["BE@RBRICK", "티셔츠", "그래픽", "코튼", "화이트", "웨어러블", "팝아트"] },
  { id: "diamant-crossbody", kind: "MCM ICON", name: "Diamant 비세토스 레더 믹스 3D 크로스바디", description: "바바리안 다이아몬드에서 영감받은 입체 구조와 비세토스를 결합한 크로스바디", officialUrl: "https://kr.mcmworldwide.com/ko_KR/%EB%82%A8%EC%84%B1/%EA%B0%80%EB%B0%A9/%ED%81%AC%EB%A1%9C%EC%8A%A4%EB%B0%B1/diamant-%EB%B9%84%EC%84%B8%ED%86%A0%EC%8A%A4-%EB%A0%88%EB%8D%94-%EB%AF%B9%EC%8A%A4-3d-%ED%81%AC%EB%A1%9C%EC%8A%A4%EB%B0%94%EB%94%94/MMRGSAK02CO001.html", image: "/products/mcm-diamant-crossbody.jpg", tags: ["Diamant", "비세토스", "크로스바디", "다이아몬드", "조형", "입체", "꼬냑"] },
  { id: "taekwondo-rabbit-charm", kind: "MCM COLLECTION", name: "Aren 비세토스 태권도 레빗 참", description: "MCM의 레빗 캐릭터에 태권도복과 블랙 비세토스 디테일을 더한 참", officialUrl: "https://kr.mcmworldwide.com/ko_KR/%EB%82%A8%EC%84%B1/%ED%8C%A8%EC%85%98%EC%86%8C%ED%92%88/%EB%AA%A8%EB%91%90%EB%B3%B4%EA%B8%B0/aren-%EB%B9%84%EC%84%B8%ED%86%A0%EC%8A%A4-%ED%83%9C%EA%B6%8C%EB%8F%84-%EB%A0%88%EB%B9%97-%EC%B0%B8/MXZGSTA13BW001.html", image: "/products/mcm-taekwondo-rabbit-charm.jpg", tags: ["레빗", "태권도", "참", "캐릭터", "블랙", "화이트", "한국", "팝"] },
  { id: "aren-ew-shoulder", kind: "MCM ICON", name: "Aren 비세토스 E/W 숄더백", description: "동서 방향의 간결한 실루엣에 시그니처 비세토스를 담은 데일리 숄더백", officialUrl: "https://kr.mcmworldwide.com/ko_KR/%EC%97%AC%EC%84%B1/%ED%95%B8%EB%93%9C%EB%B0%B1/%EC%88%84%EB%8D%94%EB%B0%B1-%ED%81%AC%EB%A1%9C%EC%8A%A4%EB%B0%B1/aren-%EB%B9%84%EC%84%B8%ED%86%A0%EC%8A%A4-e%2Fw-%EC%88%84%EB%8D%94%EB%B0%B1/MWSGSTA02CO001.html", image: "/products/mcm-aren-ew-shoulder.jpg", tags: ["Aren", "비세토스", "숄더백", "가로형", "미니멀", "꼬냑", "데일리"] },
  { id: "stark-maxi-black", kind: "MCM ICON", name: "Stark 맥시 모노그램 레더 백팩", description: "이탈리안 풀 그레인 레더에 맥시 모노그램을 엠보싱한 모노크롬 Stark 백팩", officialUrl: "https://kr.mcmworldwide.com/ko_KR/%EB%82%A8%EC%84%B1/%EA%B0%80%EB%B0%A9/%EB%B0%B1%ED%8C%A9/stark-%EB%A7%A5%EC%8B%9C-%EB%AA%A8%EB%85%B8%EA%B7%B8%EB%9E%A8-%EB%A0%88%EB%8D%94-%EB%B0%B1%ED%8C%A9/MMKGSVE04BK001.html", image: "/products/mcm-stark-maxi-black.jpg", tags: ["Stark", "백팩", "블랙", "모노크롬", "풀 그레인 레더", "엠보싱", "바우하우스"] },
];
